package com.groq.sdk.models.chat;

/**
 * Represents a tool call generated by the model in an assistant message.
 * 
 * @author Debajit Kumar Phukan
 * @since 31-Aug-2025
 * @version 1.0.0
 * @see ChatMessage
 * @see ChatCompletion
 */
public class ChatToolCall {
    private String id;
    private String type = "function";
    private ToolCallFunction function;
    
    /**
     * Default constructor.
     */
    public ChatToolCall() {}
    
    /**
     * Gets the ID of the tool call.
     * 
     * @return the tool call ID
     */
    public String getId() { 
        return id; 
    }
    
    /**
     * Sets the ID of the tool call.
     * 
     * @param id the tool call ID
     */
    public void setId(String id) { 
        this.id = id; 
    }
    
    /**
     * Gets the type of the tool (always "function").
     * 
     * @return the tool type
     */
    public String getType() { 
        return type; 
    }
    
    /**
     * Sets the type of the tool.
     * 
     * @param type the tool type
     */
    public void setType(String type) { 
        this.type = type; 
    }
    
    /**
     * Gets the function call details.
     * 
     * @return the function call
     */
    public ToolCallFunction getFunction() { 
        return function; 
    }
    
    /**
     * Sets the function call details.
     * 
     * @param function the function call
     */
    public void setFunction(ToolCallFunction function) { 
        this.function = function; 
    }
    
    /**
     * Represents the function call within a tool call.
     */
    public static class ToolCallFunction {
        private String name;
        private String arguments;
        
        /**
         * Default constructor.
         */
        public ToolCallFunction() {}
        
        /**
         * Gets the name of the function to call.
         * 
         * @return the function name
         */
        public String getName() { 
            return name; 
        }
        
        /**
         * Sets the name of the function to call.
         * 
         * @param name the function name
         */
        public void setName(String name) { 
            this.name = name; 
        }
        
        /**
         * Gets the arguments to call the function with (as JSON string).
         * 
         * @return the function arguments as JSON
         */
        public String getArguments() { 
            return arguments; 
        }
        
        /**
         * Sets the arguments to call the function with (as JSON string).
         * 
         * @param arguments the function arguments as JSON
         */
        public void setArguments(String arguments) { 
            this.arguments = arguments; 
        }
    }
}